version: "3.7"
services:
  zk:
    image: zookeeper:latest
    container_name: zk
    ports:
      - "2181:2181"

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - "3306:3306"

